# Generated by Django 4.0.3 on 2022-03-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestApi',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('followed', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
